Portfolio header section
muhammedb8826/Portfolio-setup-and-mobile-first pull request #1
Opened 2023-01-13 19:42 UTC by muhammedb8826

2023-01-13 20:01 UTC, Lizdev-05 requested changes
Hi @muhammedb8826, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/oFeYuQKteOf0xEsCtj/giphy-downsized-medium.gif"/>

## Invalid Code Review Request

You have submitted a project, that is not passing the linter test. Kindly fix and resubmit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 21:21 UTC, NahnahAJ reviewed
Hi @muhammedb8826 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media4.giphy.com/media/3o6wrebnKWmvx4ZBio/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project, that has an incomplete README file, an invalid MIT license and a Pull request without a good description.

:exclamation: :exclamation: Kindly fix your Pull Request title as requested [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md), it should have a descriptive title telling you what changes are inside. Also please fix the Pull Request description section, it should have a short summary describing the introduced changes :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 21:21 UTC, NahnahAJ commented on README.md
> +- [📝 License](#license)
:exclamation: :exclamation: Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections are present in your README file.
- The only optional section is the FAQ. However, I noticed that you deleted some of the sections please make sure to include all of them. This is crucial to have a professional repository. :ok_hand:
- Please remove all the instructions targeting you. For example: "Describe how a new developer could make use of your project." 
- Lastly, your MIT license doesn't contain your details. You can use this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to learn how to add an MIT license to your project properly. :wink:

2023-01-14 00:45 UTC, RaoAkif reviewed
## STATUS: INVALID CODE REVIEW REQUEST :x:

Hi @muhammedb8826, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  :x:

You have submitted a Pull Request, that doesn't contain any description. Please describe in key points, what did you do in this pull request.
![image](https://user-images.githubusercontent.com/61361037/212442104-44f796a8-a870-4a18-97eb-1381324b9b65.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-14 00:50 UTC, RaoAkif commented
Hi @muhammedb8826, Your Pull Request is being rejected again and again. Apologies that you are having a hard time getting through. But these are some basic steps that you must have to pass through.
- Customized README, provided by Microverse.
- Descriptive Pull Request Title & Description
- Correct Linter Setup & All Linters Passing

2023-01-14 06:37 UTC, binhussen requested changes
Hi @muhammedb8826 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 06:37 UTC, binhussen commented on index.html
> +        <a href="#">My Logo</a>
- Kindly, your logo is not part of the navigation, please make your logo outside `nav`  tag.👌👍

2023-01-14 06:37 UTC, binhussen commented on index.html
> +        <div class="content">
- Great job for using semantic tags, 👍👍 I think It is better to use a section outside the `header`. kindly use the below format 👇
```
<header>
</header>
<main>
   <section>
        .......
   </section>
</main>
<footer>
</footer>
````

2023-01-14 06:37 UTC, binhussen commented on index.html
> +            <h2>I’m Muhammed Glad to see you!</h2>
- Kindly, your main title is an `h1` tag. for semantic and search engines. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. 👍👍

2023-01-14 06:37 UTC, binhussen commented on index.html
> +            </div>
- Kindly, your social list of icons has to be a  `ul` tag to group them, and a `li` per icon, for sematic reasons 👍👍

2023-01-14 12:19 UTC, christianbiring1 approved these changes
Hi @muhammedb8826 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![APPROVED](https://user-images.githubusercontent.com/97100091/212471299-8f427186-fe7b-410e-9828-9630e6b0407e.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] Good README file :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 12:19 UTC, christianbiring1 commented on style.css
> +  background-position: center;
[OPTIONAL]
- [ ] Kindly make sure you stick to the designs much as you can. The colors are supposed to match with the original design. kindly fix that.
`Hint:`
![image](https://user-images.githubusercontent.com/97100091/212471150-0c15b69d-5c48-4875-9a26-bf42b1cd973f.png)

You design 
![image](https://user-images.githubusercontent.com/97100091/212471014-4b3d8bb5-37e6-4214-822c-b73634f7a4cc.png)
Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/212471088-fc24da4e-fccd-43b6-9718-9388fd17f49d.png)

2023-01-14 12:46 UTC, merged