Milestone: 6 Website Accessibility Check
muhammedb8826/Portfolio-setup-and-mobile-first pull request #8
Opened 2023-01-24 20:04 UTC by muhammedb8826

## Accessibility Checking

- Title- No issues.
- Image text alternatives- Improved on the first commit.
- Text heading- No issues with text headings
- Color contrast- No issues
- Resize- No issues with resize
- Label- Added hidden form labels on the second commit.
- Moving content- No issues
- Multimedia- No issues
- Structure- No issues with the structure

2023-01-24 21:22 UTC, binhussen requested changes
Hi @muhammedb8826 , @ClintonYounge , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
-  Kindly, the title has to adequately and briefly describes the content of the page. For example: `Mohammed portfolio`👌for better accessibility 👍
-  Kindly, It would be better to implement `hover` and `focus` state for all your links to be easily identified 👍👌 Your logo hasn't have any hover and focuses so it fails color contrast, please fix it
 ![Screenshot_20230125_120946](https://user-images.githubusercontent.com/52010789/214418490-4cbf2d04-560f-470f-8c46-9c4205617d34.png)
- [Optional] Kindly, I think it would be better relative measurements like `em`, `rem` instead of absolute measurements, to make your content resizable 👌👍

## Optional suggestions
_Every comment with the [
OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 22:31 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @muhammedb8826 @ClintonYounge 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please follow the previous reviewer's advice on fixing the color contrast of your title. At the moment it isn't passing the contrast check, you can use [this tool](https://www.aditus.io/button-contrast-checker/) to check the color contrast before submitting your project again. Remember that having a good contrast will make your site easier to read for those who have reduced visibility! 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/214435708-d6286187-290f-485d-b068-1be92091db94.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 00:28 UTC, ClintonYounge commented
@muhammedb8826 Message me on Slack.

2023-01-25 00:38 UTC, IngDavidTM approved these changes
Hi @muhammedb8826 and @ClintonYounge   🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 00:39 UTC, merged

2023-01-25 10:36 UTC, muhammedb8826 commented
Link added to pull request description

2023-01-25 10:37 UTC, muhammedb8826 reviewed
Accessibility issues improved to make the website more accessible

2023-01-25 10:37 UTC, muhammedb8826 commented on index.html
> +    <title>Muhammed's Portfolio</title>
Title changed to my own name

2023-01-25 10:37 UTC, muhammedb8826 commented on index.html
> +            <a href="#"><img src="./assets/Vector (3).svg" alt="angelist" /></a>
Alt text improved for medium and angelist icons

2023-01-25 10:37 UTC, muhammedb8826 commented on index.html
>              id="form-text-area"
Label text added to improve accessibilty

2023-01-25 11:02 UTC, muhammedb8826 reviewed
All color contrast fixed to improve its accessibility

2023-01-25 11:09 UTC, muhammedb8826 reviewed
Color contrast fixed

2023-01-25 11:09 UTC, muhammedb8826 commented on style.css
> +  color: #5e6c84;
Color contrast issues fixed, to improve accessibility of the web page

2023-01-25 11:10 UTC, muhammedb8826 commented
Color contrast fixed